### ISSUE TITLE
Clicking tableView column header

### ISSUE THREAD

**Issue by protektik** [TestFX/TestFX#541]
I was using version 4.0.4-alpha where, when i done this:
clickOn(tableColumnId);
it clicked on tableColumn header, which was expected behavior. Now I moved to 4.0.11-alpha and the same code:
clickOn(tableColumnId);
clicks on specified column, but somewhere in the data area. Is there a way to click on tableColumn header in 4.0.11-alpha?

## Specifications

  - Version: 4.0.11-alpha
  - Platform: windows 7

**Comment by brcolow** [comment]
Hmmm that's an interesting regression. Not sure how any of the changes could cause that. Do you have a simple test case that shows the expected vs. actual behavior?

**Comment by brcolow** [comment]
On `4.0.12-alpha` calling `clickOn("#tableColumn")` clicks on the first row, for me. I will investigate what changed from `4.0.4-alpha` w.r.t. this issue.

**Comment by brcolow** [comment]
Something is different between the bounds returned by `4.0.4-alpha` and `master`:

These print statements can be seen in https://github.com/brcolow/TestFX/tree/issue-541-2

```
master:
    point locator: org.testfx.service.locator.impl.PointLocatorImpl@13842bad
    pointPosition: CENTER
    PointQueryUtils#computePositionFactors, returning: Point2D [x = 0.5, y = 0.5]
    boundsInSceneFor: TableColumn$1$1[id=tableColumn0, styleClass=cell indexed-cell table-cell table-column]'null'
    sceneBounds: BoundingBox [minX:1.0, minY:234.0, minZ:0.0, width:57.0, height:29.0, depth:0.0, maxX:58.0, maxY:263.0, maxZ:0.0]
    Returning: BoundingBox [minX:1597.0, minY:581.0, minZ:0.0, width:57.0, height:29.0, depth:0.0, maxX:1654.0, maxY:610.0, maxZ:0.0]
    pointQuery: CallableBoundsPointQuery [position = Point2D [x = 0.5, y = 0.5], offset = Point2D [x = 0.0, y = 0.0], bounds = BoundingBox [minX:1597.0, minY:581.0, minZ:0.0, width:57.0, height:29.0, depth:0.0, maxX:1654.0, maxY:610.0, maxZ:0.0]]
    boundsInSceneFor: TableColumn$1$1[id=tableColumn0, styleClass=cell indexed-cell table-cell table-column]'null'
    sceneBounds: BoundingBox [minX:1.0, minY:234.0, minZ:0.0, width:57.0, height:29.0, depth:0.0, maxX:58.0, maxY:263.0, maxZ:0.0]
    Returning: BoundingBox [minX:1597.0, minY:581.0, minZ:0.0, width:57.0, height:29.0, depth:0.0, maxX:1654.0, maxY:610.0, maxZ:0.0]
    bounds: BoundingBox [minX:1597.0, minY:581.0, minZ:0.0, width:57.0, height:29.0, depth:0.0, maxX:1654.0, maxY:610.0, maxZ:0.0]
    positionFactors: Point2D [x = 0.5, y = 0.5]
    PointQueryUtils#atPositionFactors returning: Point2D [x = 1625.5, y = 595.5]
    BoundsPointQuery#query.point: Point2D [x = 1625.5, y = 595.5]
    BoundsPointQuery#query.offet: Point2D [x = 0.0, y = 0.0]
    boundsInSceneFor: TableColumn$1$1[id=tableColumn0, styleClass=cell indexed-cell table-cell table-column]'null'
    sceneBounds: BoundingBox [minX:1.0, minY:234.0, minZ:0.0, width:57.0, height:29.0, depth:0.0, maxX:58.0, maxY:263.0, maxZ:0.0]
    Returning: BoundingBox [minX:1597.0, minY:581.0, minZ:0.0, width:57.0, height:29.0, depth:0.0, maxX:1654.0, maxY:610.0, maxZ:0.0]
    bounds: BoundingBox [minX:1597.0, minY:581.0, minZ:0.0, width:57.0, height:29.0, depth:0.0, maxX:1654.0, maxY:610.0, maxZ:0.0]
    positionFactors: Point2D [x = 0.5, y = 0.5]
    PointQueryUtils#atPositionFactors returning: Point2D [x = 1625.5, y = 595.5]
    BoundsPointQuery#query.point: Point2D [x = 1625.5, y = 595.5]
    BoundsPointQuery#query.offet: Point2D [x = 0.0, y = 0.0]
```

v4.0.4-alpha:

```
    point locator: org.testfx.service.locator.impl.PointLocatorImpl@6fad4e8b
    pointPosition: CENTER
    PointQueryUtils#computePositionFactors, returning: Point2D [x = 0.5, y = 0.5]
    boundsInSceneFor: TableColumnHeader[id=tableColumn0, styleClass=column-header table-column]
    sceneBounds: BoundingBox [minX:1.0, minY:1.0, minZ:0.0, width:56.884765625, height:30.0, depth:0.0, maxX:57.884765625, maxY:31.0, maxZ:0.0]
    Returning: BoundingBox [minX:1597.0, minY:348.0, minZ:0.0, width:56.884765625, height:30.0, depth:0.0, maxX:1653.884765625, maxY:378.0, maxZ:0.0]
    pointQuery: CallableBoundsPointQuery [position = Point2D [x = 0.5, y = 0.5], offset = Point2D [x = 0.0, y = 0.0], bounds = BoundingBox [minX:1597.0, minY:348.0, minZ:0.0, width:56.884765625, height:30.0, depth:0.0, maxX:1653.884765625, maxY:378.0, maxZ:0.0]]
    boundsInSceneFor: TableColumnHeader[id=tableColumn0, styleClass=column-header table-column]
    sceneBounds: BoundingBox [minX:1.0, minY:1.0, minZ:0.0, width:56.884765625, height:30.0, depth:0.0, maxX:57.884765625, maxY:31.0, maxZ:0.0]
    Returning: BoundingBox [minX:1597.0, minY:348.0, minZ:0.0, width:56.884765625, height:30.0, depth:0.0, maxX:1653.884765625, maxY:378.0, maxZ:0.0]
    bounds: BoundingBox [minX:1597.0, minY:348.0, minZ:0.0, width:56.884765625, height:30.0, depth:0.0, maxX:1653.884765625, maxY:378.0, maxZ:0.0]
    positionFactors: Point2D [x = 0.5, y = 0.5]
    PointQueryUtils#atPositionFactors returning: Point2D [x = 1625.4423828125, y = 363.0]
    BoundsPointQuery#query.point: Point2D [x = 1625.4423828125, y = 363.0]
    BoundsPointQuery#query.offet: Point2D [x = 0.0, y = 0.0]
    boundsInSceneFor: TableColumnHeader[id=tableColumn0, styleClass=column-header table-column]
    sceneBounds: BoundingBox [minX:1.0, minY:1.0, minZ:0.0, width:56.884765625, height:30.0, depth:0.0, maxX:57.884765625, maxY:31.0, maxZ:0.0]
    Returning: BoundingBox [minX:1597.0, minY:348.0, minZ:0.0, width:56.884765625, height:30.0, depth:0.0, maxX:1653.884765625, maxY:378.0, maxZ:0.0]
    bounds: BoundingBox [minX:1597.0, minY:348.0, minZ:0.0, width:56.884765625, height:30.0, depth:0.0, maxX:1653.884765625, maxY:378.0, maxZ:0.0]
    positionFactors: Point2D [x = 0.5, y = 0.5]
    PointQueryUtils#atPositionFactors returning: Point2D [x = 1625.4423828125, y = 363.0]
    BoundsPointQuery#query.point: Point2D [x = 1625.4423828125, y = 363.0]
    BoundsPointQuery#query.offet: Point2D [x = 0.0, y = 0.0]
```

The scene bounds are different, and I am not sure why. This is mostly just a reference for myself for future work on this (not expecting it to be understood by others).
