### ISSUE TITLE
Java 11 Headless Testing NoClassDefFoundError com/sun/glass/ui/Robot

### ISSUE THREAD

**Issue by zero57** [TestFX/TestFX#640]
## Expected Behavior
Should be able to run TestFX in Headless mode using the glass robot.

## Actual Behavior
Can't run TestFX in headless mode using glass robot

## Specifications

  - Version: OpenJDK 11 (`11b28-1` on Arch)
  - Platform: Arch Linux x64

I have the following dependencies in my `pom.xml`

```
        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-base</artifactId>
            <version>11</version>
        </dependency>

        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-controls</artifactId>
            <version>11</version>
        </dependency>

        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-fxml</artifactId>
            <version>11</version>
        </dependency>

        <dependency>
            <groupId>com.jfoenix</groupId>
            <artifactId>jfoenix</artifactId>
            <version>9.0.6</version>
        </dependency>

        <dependency>
            <groupId>org.testfx</groupId>
            <artifactId>testfx-core</artifactId>
            <version>4.0.14-alpha</version>
        </dependency>

        <dependency>
            <groupId>org.testfx</groupId>
            <artifactId>testfx-junit5</artifactId>
            <version>4.0.14-alpha</version>
        </dependency>

        <dependency>
            <groupId>org.testfx</groupId>
            <artifactId>openjfx-monocle</artifactId>
            <version>jdk-11+23</version>
        </dependency>
```

And when I run `mvn test -Djava.awt.headless=true -Dtestfx.headless=true -Dtestfx.robot=glass -Dprism.order=sw` I get the following error messages in my tests
```
--- Exception in Async Thread ---
java.lang.NoClassDefFoundError: com/sun/glass/ui/Robot
        org.testfx.service.adapter.impl.GlassRobotAdapter.robotCreate(GlassRobotAdapter.java:53)
        org.testfx.service.adapter.impl.GlassRobotAdapter.useRobot(GlassRobotAdapter.java:158)
        org.testfx.service.adapter.impl.GlassRobotAdapter.lambda$getMouseLocation$4(GlassRobotAdapter.java:91)
        java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
        java.base/java.security.AccessController.doPrivileged(Native Method)
        com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
        com.sun.glass.ui.monocle.RunnableProcessor.runLoop(RunnableProcessor.java:92)
        com.sun.glass.ui.monocle.RunnableProcessor.run(RunnableProcessor.java:51)
        java.base/java.lang.Thread.run(Thread.java:834)
```

Trying on Azure pipeline, with the following config `azure-pipelines.yml`:

```
pool:
  vmImage: 'Ubuntu 16.04'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    options: '-Djava.awt.headless=true -Dtestfx.robot=glass -Dtestfx.headless=true -Dprism.order=sw'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    goals: 'package'
``` 

I've also tried running it in Travis CI with the following config `.travis.yml`:
```
language: java
sudo: false

matrix:
  include:
    - os: linux
      dist: trusty
      jdk: openjdk11
      env:
        - _JAVA_OPTIONS="--add-opens=java.base/java.util=ALL-UNNAMED -Djava.awt.headless=true -Dtestfx.robot=glass -Dtestfx.headless=true -Dprism.order=sw"

addons:
  apt:
    packages:
      - openjdk-11-jdk

script: mvn test
```

I still get the same error.

EDIT: `java -version` gives
```
openjdk version "11" 2018-09-25
OpenJDK Runtime Environment 18.9 (build 11+28)
OpenJDK 64-Bit Server VM 18.9 (build 11+28, mixed mode)
```
and `mvn -version` gives
```
Apache Maven 3.5.4 (NON-CANONICAL_2018-09-08T01:02:16+02:00_root; 2018-09-07T19:02:16-04:00)
Maven home: /opt/maven
Java version: 11, vendor: Oracle Corporation, runtime: /usr/lib/jvm/java-11-openjdk
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.18.16-arch1-1-arch", arch: "amd64", family: "unix"
```

Interestingly enough, I looked into the source code and it should attempt to search for `Class.forName("javafx.scene.robot.Robot");` but it doesn't. Also, it searches for `Class.forName("com.sun.glass.ui.Robot");`, but I don't see this on my system. However, I do see `"com.sun.glass.ui.GlassRobot"` when I try to import it in my code (I also see `javafx.scene.robot.Robot` when I attempt to import then in my code using IntelliJ). Perhaps it was renamed?

I suppose it can't find `javafx.scene.robot.Robot` because I'm using OpenJFX as a maven dependency?
